"""Mapa de municipios de Boyacá a provincia.

Se mantiene como diccionario en Python por rendimiento:
- evita lecturas de disco en cada interacción,
- acceso O(1) por llave,
- y queda versionado junto al código.
"""

MAPA_PROVINCIAS = {
    # OCCIDENTE
    "otanche": "Occidente",
    "pauna": "Occidente",
    "san pablo de borbur": "Occidente",
    "quipama": "Occidente",
    "la victoria": "Occidente",
    "muzo": "Occidente",
    "maripi": "Occidente",
    "coper": "Occidente",
    "buenavista": "Occidente",
    "tunungua": "Occidente",
    "briceno": "Occidente",
    "caldas": "Occidente",
    "saboya": "Occidente",
    "chiquinquira": "Occidente",
    "san miguel de sema": "Occidente",
    # RICAURTE
    "santana": "Ricaurte",
    "san jose de pare": "Ricaurte",
    "chitaraque": "Ricaurte",
    "togui": "Ricaurte",
    "moniquira": "Ricaurte",
    "santa sofia": "Ricaurte",
    "gachantiva": "Ricaurte",
    "arcabuco": "Ricaurte",
    "sutamarchan": "Ricaurte",
    "villa de leyva": "Ricaurte",
    "tinjaca": "Ricaurte",
    "sachica": "Ricaurte",
    "raquira": "Ricaurte",
    # CENTRO
    "samaca": "Centro",
    "ventaquemada": "Centro",
    "chiquiza": "Centro",
    "sora": "Centro",
    "cucaita": "Centro",
    "tunja": "Centro",
    "motavita": "Centro",
    "soraca": "Centro",
    "combita": "Centro",
    "oicata": "Centro",
    "chivata": "Centro",
    "siachoque": "Centro",
    "sotaquira": "Centro",
    "tuta": "Centro",
    "toca": "Centro",
    # MÁRQUEZ
    "turmeque": "Márquez",
    "umbita": "Márquez",
    "nuevo colon": "Márquez",
    "tibana": "Márquez",
    "boyaca": "Márquez",
    "jenesano": "Márquez",
    "ramiriqui": "Márquez",
    "viracacha": "Márquez",
    "cienega": "Márquez",
    "rondon": "Márquez",
    # ORIENTE
    "la capilla": "Oriente",
    "tenza": "Oriente",
    "guateque": "Oriente",
    "sutatenza": "Oriente",
    "guayata": "Oriente",
    "somondoco": "Oriente",
    "almeida": "Oriente",
    "chivor": "Oriente",
    # NEIRA
    "pachavita": "Neira",
    "chinavita": "Neira",
    "garagoa": "Neira",
    "macanal": "Neira",
    "santa maria": "Neira",
    "san luis de gaceno": "Neira",
    # LENGUPÁ
    "zetaquira": "Lengupá",
    "miraflores": "Lengupá",
    "berbeo": "Lengupá",
    "san eduardo": "Lengupá",
    "campohermoso": "Lengupá",
    "paez": "Lengupá",
    # SUGAMUXI
    "tibasosa": "Sugamuxi",
    "nobsa": "Sugamuxi",
    "topaga": "Sugamuxi",
    "gameza": "Sugamuxi",
    "firavitoba": "Sugamuxi",
    "sogamoso": "Sugamuxi",
    "mongui": "Sugamuxi",
    "mongua": "Sugamuxi",
    "pesca": "Sugamuxi",
    "iza": "Sugamuxi",
    "cuitiva": "Sugamuxi",
    "tota": "Sugamuxi",
    "aquitania": "Sugamuxi",
    # TUNDAMA
    "paipa": "Tundama",
    "duitama": "Tundama",
    "santa rosa de viterbo": "Tundama",
    "cerinza": "Tundama",
    "floresta": "Tundama",
    "belen": "Tundama",
    "busbanza": "Tundama",
    "tutaza": "Tundama",
    "corrales": "Tundama",
    # LA LIBERTAD
    "pisba": "La Libertad",
    "paya": "La Libertad",
    "labranzagrande": "La Libertad",
    "pajarito": "La Libertad",
    # VALDERRAMA
    "beteitiva": "Valderrama",
    "paz de rio": "Valderrama",
    "tasco": "Valderrama",
    "socha": "Valderrama",
    "socota": "Valderrama",
    "chita": "Valderrama",
    "jerico": "Valderrama",
    # NORTE
    "covarachia": "Norte",
    "tipacoque": "Norte",
    "san mateo": "Norte",
    "boavita": "Norte",
    "soata": "Norte",
    "la uvita": "Norte",
    "susacon": "Norte",
    "sativanorte": "Norte",
    "sativasur": "Norte",
    # GUTIÉRREZ
    "chiscas": "Gutiérrez",
    "guican": "Gutiérrez",
    "el espino": "Gutiérrez",
    "guacamayas": "Gutiérrez",
    "panqueba": "Gutiérrez",
    "el cocuy": "Gutiérrez",
    # ESPECIALES
    "cubara": "Cubará",
    "puerto boyaca": "Puerto Boyacá",
}
